### ISSUE TITLE
Use `GitHub Actions` for publishing the package

### ISSUE THREAD

**Issue by nkilm** [nkilm/git-logs#2]
At present the project is published manually to `pypi` everytime some issue is fixed.

- **Automate the process of publishing the package to `pypi`  using GitHub Actions.**

**Comment by Shamik1836** [comment]
Hey, I would like to work on this issue, can you please assign it to me?

**Comment by nkilm** [comment]
Please state your plan on solving this issue. E.g, what resources are you going to use?

**Comment by Shamik1836** [comment]
I have found out few resources on the web and since I know and worked with python as well so I think I would be able to contribute to this issue.
